import { Dieta } from "../entities/Dieta"
import { IDIetaRepository } from "../../application/interfaces/IDietaRepository"
import { CriarDietaDTO } from "../../application/dtos/CriarDietaDTO"
import { v4 as uuidv4 } from "uuid"
import { CriarDietaResponseDTO } from "../../application/dtos/CriarDietaResponseDTO"
